(configuration-layer/declare-layers
 '(
          xingwenju-ui
          xingwenju-theming
          xingwenju-org
          xingwenju-writer
          xingwenju-services
          xingwenju-programming
 ))
